# Generated by Django 4.2.1 on 2023-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roomnum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
