# Generated by Django 4.2.1 on 2023-06-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_roomnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lan',
            new_name='lng',
        ),
    ]
