# Generated by Django 4.2.1 on 2023-05-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_lat_post_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='person',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
