# Generated by Django 4.2.1 on 2023-06-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_user_post_match_post_postuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postuser',
            new_name='user',
        ),
    ]
